### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by gregsdennis**
I've updated the stale readme to

- better explain the purpose of this repo
- invite others to participate
- start a curated list of vocabs

### CODE REVIEW

**Comment by jdesrosiers** [comment]
"JSON UI Schema" should probably be removed. It links to an empty repo the projects listed under "Known Implementations" haven't been updated since before vocabularies existed.

"JSON API Documentation Schema" should probably be removed as well. I highly doubt anyone is working on it. It says it's based on hyper-schema, which is not currently being maintained, but even if it was, it wouldn't make sense to use hyper-schema for API description anyway.

**Comment by gregsdennis** [comment]
The repo isn't empty; all the code is on a secondary branch, `Development` or some sort.  Maybe I can link directly to that branch?

Fair points, though. I had considered removing the docs one, but didn't want to step on toes.

**Comment by jdesrosiers** [comment]
The most recent activity I'm seeing on any branch on any of the repos linked is 3 years old. If this vocabulary exists, the links are pointing to the wrong place.

https://github.com/json-schema-form/json-schema-form/branches
https://github.com/json-schema-form/json-schema-form-core/branches
https://github.com/Anthropic/angular-schema-form/branches
https://github.com/json-schema-form/angular-schema-form/branches

**Comment by jdesrosiers** [comment]
I think each listed vocabulary should also list the `$id` of the vocabulary that is defined and a link to download the meta-schema if the `$id` is not network accessible.

**Comment by gregsdennis** [comment]
Yeah, I can remove them until we have an indication that they should be here.

**Comment by gregsdennis** [comment]
I accidently pushed here instead of my fork.  I revert if needed.

**Comment by jdesrosiers** [comment]
No need to revert, but I'd still like to see some of the changes I suggested.

**Comment by gregsdennis** [comment]
I _did_ do some of the changes you requested. But because I just committed to this repo (not my fork) that don't appear in the PR.  Check out the README on master.

**Comment by jdesrosiers** [comment]
Ahh, sorry. Looks good. Thanks

**Pull request merged**
